services:
  db:
    image: postgres:16-alpine
    container_name: lotterydb
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=Dead_Pigeon
    ports:
      - '5432:5432'
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d/