name: Deploy Game

on:
  push:
    branches:
      - master

jobs:
    deploy-fe:
        name: Deploy Frontend
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - name: Install dependencies
              run: |
                cd ./client
                pwd
                npm install

            - name: Build the frontend
              run: |
                cd ./client
                pwd
                npm run build

            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                key: ${{ secrets.SSH_KEY }}
                known_hosts: 'just-a-temp-bypass'

            - name: Adding Known Hosts
              run: ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts

            - name: Deploy
              run: |
                cd ./client/dist
                scp -r -f . ${{ secrets.SSH_USER }}@${{ secrets.IP }}:${{ secrets.PATH }}

            - name: Archive npm failure logs
              uses: actions/upload-artifact@v4
              if: failure()
              with:
                name: npm-logs
                path: ~/.npm/_logs
                retention-days: 1